library(dplyr)

classes<-c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric")
data<-read.csv("household_power_consumption.txt",header=TRUE,sep=";",colClasses=classes,na.strings = "?")
data<-data%>%select(Date:Sub_metering_3)
data<-data%>%filter(Date=="1/2/2007"|Date=="2/2/2007")
par(mfrow=c(1,1),mar=c(4,4,2,2))
x<-seq(0,nrow(data)-1,by=1)
data<-data%>%mutate(Time=x)
m<-nrow(filter(data,Date=="1/2/2007"))
with(data,plot(Time,Global_active_power,ylab="Global active power (kilowatts)",xaxt="n",xlab="",main="",type="line"))
axis(1,at=c(0,m,nrow(data)),labels=c("Thu","Fri","Sat"))
dev.copy(png,"plot2.png")
dev.off()
